services:

  chromadb:
    container_name: chroma
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - ./chroma_data:/chroma/chroma
  #    networks:
  #      - ragapp-network

  effectzgpt_server:
    container_name: server
    image: effectzai/effectzgpt_b
    ports:
      - 5002:5000
    volumes:
      - ./effectzgpt/backend/config:/app/config
      - ./effectzgpt/backend/data:/app/data
      - ./effectzgpt/backend/chromadb:/app/chromadb
    environment:
      - APP_PORT=${APP_PORT}
      - TOP_K=${TOP_K}
      - STREAM_TIMEOUT=${STREAM_TIMEOUT}
      - VECTOR_STORE_PROVIDER=${VECTOR_STORE_PROVIDER}
      - CHROMA_PATH=${CHROMA_PATH}
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
      - MODEL_PROVIDER=${MODEL_PROVIDER}
      - MODEL=${MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_DIM=${EMBEDDING_DIM}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SYSTEM_PROMPT=You are Jordan government assistant , you only know about the services provided by the Jordan government .
      - COHERE_API_KEY=${COHERE_API_KEY}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
  #    networks:
  #      - ragapp-network
  #  links:
  #    - chromadb
    command: >
      /bin/sh -c
      "
      poetry run generate &&
      python main.py"

  effectzgpt_ui:
    container_name: ui
    image: effectzai/effectzgpt_f
    ports:
      - 5001:3000
    environment:
      - NEXT_PUBLIC_CHAT_API=${NEXT_PUBLIC_CHAT_API}
    volumes:
      - ./effectzgpt/frontend/config:/app/config
      - ./effectzgpt/frontend/cache:/app/cache
    links:
      - effectzgpt_server
  #  networks:
  #    - ragapp-network

  effectzgpt:
    container_name: effectzgpt_a
    image: effectzai/effectzgpt
    ports:
      - 5000:3000
    volumes:
      - ./effectzgpt/backend/config:/app/backend/config
      - ./effectzgpt/backend/data:/app/backend/data
      - ./effectzgpt/frontend/config:/app/frontend/config
      - ./effectzgpt/frontend/cache:/app/frontend/cache
      - ./effectzgpt/backend/chromadb:/app/backend/chromadb
    environment:
      - NEXT_PUBLIC_CHAT_API=${NEXT_PUBLIC_CHAT_API}
      - APP_PORT=${APP_PORT}
      - TOP_K=${TOP_K}
      - STREAM_TIMEOUT=${STREAM_TIMEOUT}
      - VECTOR_STORE_PROVIDER=${VECTOR_STORE_PROVIDER}
      - CHROMA_PATH=${CHROMA_PATH}
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
      - MODEL_PROVIDER=${MODEL_PROVIDER}
      - MODEL=${MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_DIM=${EMBEDDING_DIM}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SYSTEM_PROMPT=You are Jordan government assistant , you only know about the services provided by the Jordan government .
      - COHERE_API_KEY=${COHERE_API_KEY}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
    command: >
      /bin/sh -c
      "
      cd /app/backend &&
      poetry run generate &&
      nohup python main.py > output_b.log 2>&1 &
      cd /app/frontend &&
      exec npm run start"

  effectz_whatsapp:
    image: effectzai/effectzgpt_whatsapp 
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    environment:
      - WHATSAPP_WEBHOOK_VERIFY_TOKEN=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      - EFFECTZGPT_ENDPOINT=${EFFECTZGPT_ENDPOINT}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_BUSINESS_ACCOUNT_ID=${WHATSAPP_BUSINESS_ACCOUNT_ID}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
  
  effectz_messenger:
    image: effectzai/effectzgpt_messenger 
    ports:
      - "${MESSENGER_PORT}:${MESSENGER_PORT}"
    environment:
      - MESSENGER_WEBHOOK_VERIFY_TOKEN=${MESSENGER_WEBHOOK_VERIFY_TOKEN}
      - MESSENGER_ACCESS_TOKEN=${MESSENGER_ACCESS_TOKEN}
      - EFFECTZGPT_ENDPOINT=${EFFECTZGPT_ENDPOINT}

#networks:
#  ragapp-network: