services:
  chromadb:
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - ./chroma_data:/chroma/chroma
    networks:
      - ragapp-network

  effectzgpt_server:
    image: effectzai/effectzgpt_b
    ports:
      - 5000:5000
    volumes:
      - ./effectzgpt/backend/config:/app/config
      - ./effectzgpt/backend/data:/app/data
#      - ./effectzgpt/backend/chromadb:/app/chromadb
    environment:
      - APP_PORT=5000
      - TOP_K=10
      - STREAM_TIMEOUT=60000
      - VECTOR_STORE_PROVIDER=chroma
#      - CHROMA_PATH=./chromadb
      - CHROMA_COLLECTION=default
      - MODEL_PROVIDER=openai
      - MODEL=gpt-4o
      - EMBEDDING_MODEL=text-embedding-3-large
      - EMBEDDING_DIM=1024
      - LLAMA_CLOUD_API_KEY=
      - OPENAI_API_KEY=
      - SYSTEM_PROMPT=You are Jordan government assistant , you only know about the services provided by the Jordan government .
      - COHERE_API_KEY=Yp0wADuPD6aMfOcfuSzNs7pru2Kqy3jloizXMECp
      - CHROMA_HOST=host.docker.internal
      - CHROMA_PORT=8000
    networks:
      - ragapp-network
    depends_on:
      - chromadb
    command: >
      /bin/sh -c
      "poetry run generate &&
      python main.py"

  effectzgpt_ui:
    image: effectzai/effectzgpt_f
    ports:
      - 8001:3000
    environment:
      - NEXT_PUBLIC_CHAT_API=http://localhost:5000/api/chat
    volumes:
      - ./effectzgpt/frontend/config:/app/config
      - ./effectzgpt/frontend/cache:/app/cache
    networks:
      - ragapp-network
    depends_on:
      - effectzgpt_server

networks:
  ragapp-network: