#db:
#- queries: []
#  uri: null
#- queries: []
#  uri: null
file:
  # use_llama_parse: Use LlamaParse if `true`. Needs a `LLAMA_CLOUD_API_KEY` from https://cloud.llamaindex.ai set as environment variable
  use_llama_parse: false
#web:
#  driver_arguments: ["--remote-debugging-port=9222"]
#  urls: [
#    { base_url: ,
#      prefix: ,
#      max_depth:
#    }
#  ]