version: '3.8'

services:
  whatsapp-integration:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - EFFECTZGPT_ENDPOINT=${EFFECTZGPT_ENDPOINT}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_BUSINESS_ACCOUNT_ID=${WHATSAPP_BUSINESS_ACCOUNT_ID}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - CLOUD_API_VERSION=${CLOUD_API_VERSION:-17.0}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  whatsapp-network:
    driver: bridge

volumes:
  logs:
